### PR TITLE
March 2019 Update to IoT and the Smart City

### PR DESCRIPTION
**Pull request by mrfalafel**

### CODE REVIEW

**Comment by mrfalafel** [comment]
Thanks @waltermyersiii 
Can you point to one of the references?
Thanks a million

**Comment by toddwhitehead** [comment]
The labvm (https://github.com/solliancenet/LABVM) still refers to "IoT for Business" as does the section in MCW-IoT-And-The-Smart-City/blob/master/Hands-on%20lab/Before%20the%20HOL.md that refers to that repo (Task 1 step2)

**Comment by mrfalafel** [comment]
Thanks @toddwhitehead and @waltermyersiii 
I asked Solliance to update the LabVM to the new name, I don't have access to that repository to commit the change. It should be today sometime hopefully.
The before the HOL.md file can not be changed until the PR is approved due to the links that have to be set after the release of the new MCW.  I will do so immediately after the release of the MCW.
Thanks

**Comment by mrfalafel** [comment]
The LabVM naming and screenshot is fixed.
The before the hol.md has changed awaiting the release of the update to assign correct links.

**Pull request merged**
